[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
MCMRSimulator = "eac06e4d-a854-4bf6-b44f-54c98b0401d1"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
